{
    'itemid': r'31954',
    'allow_traps': r'0',
    'authtype': r'0',
    'description': r'',
    'follow_redirects': r'1',
    'history': r'4w',
    'http_proxy': r'',
    'inventory_link': r'0',
    'ipmi_sensor': r'',
    'jmx_endpoint': r'',
    'logtimefmt': r'',
    'master_itemid': r'0',
    'output_format': r'0',
    'params': r'',
    'password': r'',
    'port': r'',
    'post_type': r'0',
    'posts': r'',
    'privatekey': r'',
    'publickey': r'',
    'request_method': r'0',
    'retrieve_mode': r'0',
    'snmp_community': r'',
    'snmp_oid': r'',
    'snmpv3_authpassphrase': r'',
    'snmpv3_authprotocol': r'0',
    'snmpv3_contextname': r'',
    'snmpv3_privpassphrase': r'',
    'snmpv3_privprotocol': r'0',
    'snmpv3_securitylevel': r'0',
    'snmpv3_securityname': r'',
    'ssl_cert_file': r'',
    'ssl_key_file': r'',
    'ssl_key_password': r'',
    'status': r'0',
    'status_codes': r'200',
    'timeout': r'3s',
    'trapper_hosts': r'',
    'trends': r'365d',
    'units': r'',
    'username': r'',
    'valuemapid': r'1',
    'verify_host': r'0',
    'verify_peer': r'0',

    'query_fields': [
    ],


    'applications': [
        '2232',
    ],


    'preprocessing': [
    ],

},


{
    'itemid': r'31955',
    'allow_traps': r'0',
    'authtype': r'0',
    'description': r'',
    'follow_redirects': r'1',
    'history': r'1w',
    'http_proxy': r'',
    'inventory_link': r'0',
    'ipmi_sensor': r'',
    'jmx_endpoint': r'',
    'logtimefmt': r'',
    'master_itemid': r'0',
    'output_format': r'0',
    'params': r'',
    'password': r'',
    'port': r'',
    'post_type': r'0',
    'posts': r'',
    'privatekey': r'',
    'publickey': r'',
    'request_method': r'0',
    'retrieve_mode': r'0',
    'snmp_community': r'',
    'snmp_oid': r'',
    'snmpv3_authpassphrase': r'',
    'snmpv3_authprotocol': r'0',
    'snmpv3_contextname': r'',
    'snmpv3_privpassphrase': r'',
    'snmpv3_privprotocol': r'0',
    'snmpv3_securitylevel': r'0',
    'snmpv3_securityname': r'',
    'ssl_cert_file': r'',
    'ssl_key_file': r'',
    'ssl_key_password': r'',
    'status': r'1',
    'status_codes': r'200',
    'timeout': r'3s',
    'trapper_hosts': r'',
    'trends': r'365d',
    'units': r'%',
    'username': r'',
    'valuemapid': r'0',
    'verify_host': r'0',
    'verify_peer': r'0',

    'query_fields': [
    ],


    'applications': [
        '2232',
    ],


    'preprocessing': [
    ],

},


{
    'itemid': r'31956',
    'allow_traps': r'0',
    'authtype': r'0',
    'description': r'',
    'follow_redirects': r'1',
    'history': r'1w',
    'http_proxy': r'',
    'inventory_link': r'0',
    'ipmi_sensor': r'',
    'jmx_endpoint': r'',
    'logtimefmt': r'',
    'master_itemid': r'0',
    'output_format': r'0',
    'params': r'',
    'password': r'',
    'port': r'',
    'post_type': r'0',
    'posts': r'',
    'privatekey': r'',
    'publickey': r'',
    'request_method': r'0',
    'retrieve_mode': r'0',
    'snmp_community': r'',
    'snmp_oid': r'',
    'snmpv3_authpassphrase': r'',
    'snmpv3_authprotocol': r'0',
    'snmpv3_contextname': r'',
    'snmpv3_privpassphrase': r'',
    'snmpv3_privprotocol': r'0',
    'snmpv3_securitylevel': r'0',
    'snmpv3_securityname': r'',
    'ssl_cert_file': r'',
    'ssl_key_file': r'',
    'ssl_key_password': r'',
    'status': r'1',
    'status_codes': r'200',
    'timeout': r'3s',
    'trapper_hosts': r'',
    'trends': r'365d',
    'units': r's',
    'username': r'',
    'valuemapid': r'0',
    'verify_host': r'0',
    'verify_peer': r'0',

    'query_fields': [
    ],


    'applications': [
        '2232',
    ],


    'preprocessing': [
    ],

},